Comport:
  port: "/dev//ttyACM0"
  baudrate: 115200
  dotino: "./ino/proto.ino"
  warmup: 2.0

Experimental:
  cs-duration: 1.0
  Hz: 6000
  amplifer: 1.0
  samplerate: 48000
  speaker: 6
  us: 12
  us-duration: 0.065
  mean-iti: 5.0
  range-iti: 0.0
  trial: 150
  lick: 10

Metadata:
  subject: "sub-07"
  condition: "cs01-iti19-saline"
